base_url = "https://stellarburgers.nomoreparties.site/api/"
login_url = base_url + "auth/login"
ingredients_url = base_url + "ingredients"
orders_url = base_url + "orders"
register_url = base_url + "auth/register"
user_url = base_url + "auth/user"

user_email = "bulochka@yandex.ru"
user_password = "5469"
user_name = "bulka56"
new_name = "NewName"

message_incorrect_data_user = "email or password are incorrect"
message_incorrect_user = "You should be authorised"
message_incorrect_order = "Ingredient ids must be provided"
message_incorrect_register_user = "User already exists"
message_incorrect_register_data = "Email, password and name are required fields"
